### PR TITLE
Force deletion of a project

### LINKED ISSUE #16: Force deletion of a project
Currently, when a project contains repositories, the deletion of a project will fail. Registryman shall provide a CLI flag that would enable the force deletion of the Project, i.e. registryman would delete the repositories before the project deletion.

### PR DESCRIPTION
**Pull request by Kukkerem**

### CODE REVIEW

File: pkg/acr/projectapi.go [hunk 1]
```diff
@@ -41,7 +41,7 @@ func newProjectAPI(reg *registry) (*projectAPI, error) {
 // Create implements the globalregistry.ProjectAPI interface. Currently, it is
 // not implemented.
 func (p *projectAPI) Create(name string) (globalregistry.Project, error) {
-	return nil, fmt.Errorf("cannot create project in ACR: %w", globalregistry.ErrNotImplemented)
+	return nil, fmt.Errorf("cannot create project in ACR: %w", globalregistry.ErrRecoverableError)
```
Comment (szamuboy) [inline pkg/acr/projectapi.go]: I'd prefer to keep `ErrNotImplemented` and handle this error when the Action is performed in `projectAddAction.Perform`.

File: pkg/acr/projectapi.go [hunk 2]
```diff
@@ -54,7 +54,7 @@ func (p *projectAPI) GetByName(name string) (globalregistry.Project, error) {
 			return project, nil
 		}
 	}
-	return nil, nil
+	return nil, fmt.Errorf("no project found to add members: %w", globalregistry.ErrRecoverableError)
```
Comment (szamuboy) [inline pkg/acr/projectapi.go]: Why are we returning an error here? (nil,nil) is usually the "not found" return value. What has the members to do with the `GetByName` method?

File: pkg/apis/registryman.kubermatic.com/v1alpha1/testdata/test_options/global-registry-forcedelete.yaml [hunk 3]
```diff
@@ -0,0 +1,12 @@
...
+metadata:
+  name: global
+spec:
+  provider: harbor
+  role: GlobalHub
+  apiEndpoint: http://core.harbor-1.demo
+  username: admin
+  password: admin
+  options:
+    forceDelete: false
```
Comment (szamuboy) [inline pkg/apis/registryman.kubermatic.com/v1alpha1/testdata/test_options/global-registry-forcedelete.yaml]: An idea: what if you used annotations for the options rather than adding a new field?
```yaml
metadata:
  name: global
  annotations:
    registryman.kubermatic.com/forceDelete: true
```

File: pkg/config/testdata/test_other_yamls/global-project.yaml [hunk 4]
```diff
@@ -15,3 +15,4 @@ spec:
   - name: project-admins
     type: Group
     role: ProjectAdmin
+    dn: cn=Developers,ou=users,dc=example,dc=com
```
Comment (szamuboy) [inline pkg/config/testdata/test_other_yamls/global-project.yaml]: lol, I fixed this bug by removing the whole `project-admins`

File: pkg/config/testdata/test_other_yamls/local-project.yaml [hunk 5]
```diff
@@ -17,3 +17,4 @@ spec:
   - name: project-admins
     type: Group
     role: ProjectAdmin
+    dn: cn=Developers,ou=users,dc=example,dc=com
```
Comment (szamuboy) [inline pkg/config/testdata/test_other_yamls/local-project.yaml]: as above, I fixed this bug by removing the whole `project-admins`

File: pkg/globalregistry/registry.go [hunk 6]
```diff
@@ -52,6 +52,11 @@ func GetReplicationCapability(provider string) ReplicationCapabilities {
 	return cap
 }
 
+// RegistryOptions interface describes the registry options
+// coming from CLI options, or from the registry description.
+type RegistryOptions interface {
+}
+
```
Comment (szamuboy) [inline pkg/globalregistry/registry.go]: Could this be moved to `options.go`?

**Review by szamuboy — CHANGES_REQUESTED** [review]

File: pkg/config/apiobjectstore.go [hunk 7]
```diff
@@ -414,6 +417,10 @@ func (aos *ApiObjectStore) GetScanners() []*api.Scanner {
 	return scanners
 }
 
+func (apip *ApiObjectStore) GetCliOptions() globalregistry.RegistryOptions {
+	return (*ApiObjectStore)(apip).options
+}
+
```
Comment (szamuboy) [inline pkg/config/apiobjectstore.go:424]: This public method shall be documented.

**Review by szamuboy — CHANGES_REQUESTED** [review]

**Comment by szamuboy** [comment]
@Kukkerem, please update the `README.md` with the new flag.

File: pkg/acr/projectapi.go (hunk 2 above)
Comment (Kukkerem) [reply pkg/acr/projectapi.go]: In ACR without an actual repo, we don't have projects at all. We can have some logic in memberAddAction.Perform, but I thought it is better to have an error here, than creating it for different providers in the reconcile package.

The Error message is wrong, fixed!

File: pkg/acr/projectapi.go (hunk 1 above)
Comment (Kukkerem) [reply pkg/acr/projectapi.go]: done

File: pkg/config/testdata/test_other_yamls/global-project.yaml (hunk 4 above)
Comment (Kukkerem) [reply pkg/config/testdata/test_other_yamls/global-project.yaml]: will be fixed after master merge

File: pkg/config/testdata/test_other_yamls/local-project.yaml (hunk 5 above)
Comment (Kukkerem) [reply pkg/config/testdata/test_other_yamls/local-project.yaml]: will be fixed after master merge

File: pkg/globalregistry/registry.go (hunk 6 above)
Comment (Kukkerem) [reply pkg/globalregistry/registry.go]: done

File: pkg/config/apiobjectstore.go (hunk 7 above)
Comment (Kukkerem) [reply pkg/config/apiobjectstore.go:424]: done

File: pkg/globalregistry/reconciler/projectstatus.go [hunk 8]
```diff
@@ -54,10 +55,14 @@ func (pa *projectAddAction) String() string {
 
 func (pa *projectAddAction) Perform(reg globalregistry.Registry) (SideEffect, error) {
 	_, err := reg.ProjectAPI().Create(pa.Name)
-	if err != nil {
+	switch {
+	case errors.Is(err, globalregistry.ErrNotImplemented):
+		return nilEffect, nil
+	case err == nil:
+		return nilEffect, nil
```
Comment (szamuboy) [inline pkg/globalregistry/reconciler/projectstatus.go]: is this case really needed?

File: pkg/apis/registryman.kubermatic.com/v1alpha1/testdata/test_options/global-registry-forcedelete.yaml (hunk 3 above)
Comment (Kukkerem) [reply pkg/apis/registryman.kubermatic.com/v1alpha1/testdata/test_options/global-registry-forcedelete.yaml]: done

File: pkg/globalregistry/reconciler/projectstatus.go (hunk 8 above)
Comment (Kukkerem) [reply pkg/globalregistry/reconciler/projectstatus.go]: no, deleted

**Review by szamuboy — APPROVED** [review]
lgtm
